version: '3.1'

services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        restart: always
        ports:
            - "9000:9000"
        depends_on:
            - db
        environment:
            SEQ_HOST: db
            SEQ_DB: kb0tdb
            SEQ_USER: postgres
            SEQ_PW: example
            PORT: 9000
        volumes:
            - ./server/node_modules
            - ./server:/src

    ui:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - ./client/node_modules
            - ./client:/app
        ports:
            - "3000:3000"

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports:
            - 3211:5432
        volumes:
            - ./server/db/:/var/lib/postgresql/data/

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080