version: '3.1'

services:
    server:
        image: node
        restart: always
        command: npm run dev
        ports:
            - 9000:9000
        depends_on:
            - db
        working_dir: /src
        environment:
            SEQ_DB: kb0tdb
            SEQ_USER: postgres
            SEQ_PW: example
            PORT: 9000
            DATABASE_URL: postgres://postgres:example@db:3211/kb0tdb
        volumes:
            - ./server:/src

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432
        volumes:
            - ./server/db/:/var/lib/postgresql/data/

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080